### ISSUE TITLE
localhost:3001/volunter page is not displaying the volunteer details

### ISSUE THREAD

**Issue by Dhairya-A-Mehra** [rutubhanderi/Report-Generation-AP-S1#7]
Pls check the server/routes/volunteer.js file for this there you will get 
VolunteerRouter.get('/volunteer', async (_request, _response) => {
// code for fetching the data from the supabase will be written here
}
on line number 30 of this file,

Correct code will be appreciated.

**Comment by Hetosk1** [comment]
I need a screenshot please provide one
